# Base configs
# baseurl: "lzrmoos.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Wei Dai"
subtitle: "LZRMOOS"
author:  "Wei Dai"
header:
 title: "Photography"
 subtitle: "by Wei Dai"
footer:
 name: "Hello, this is Wei"
 bio: "Blah blah blah"
social_urls:
  # twitter: "https://twitter.com/"
  instagram: "https://www.instagram.com/weidvi/"
  linkedin: "https://www.linkedin.com/in/itsweidai/"
  github: "https://github.com/LZRMOOS/"
